### ISSUE TITLE
Pub get error

### ISSUE THREAD

**Issue by Mahati9** [zeeshux7860/ImageEditorPro#47]
I get this error while installing this package and its dependencies.
```
Cannot open file, path = 'C:\flutter\.pub-cache\_temp\dir5ba449a4\test\fixtures\invalid\n_structure_<.>.json' (OS Error: The filename, directory name, or volume label syntax is incorrect.
, errno = 123)
pub finished with exit code 66
```
I have tried everything based on previous answers related such as 
```
flutter clean
flutter pub cache repair
```

Also deleting pub cache folder. Nothing worked. The issue comes only when I install this image_editor_pro plugin. It is not the case with any other plugin. I thought there is some bug with this plugin. Surprisingly, no one else reported this issue. So please help me if someone tried to resolve this

**Comment by Purus** [comment]
Same with my case too.. unable to solve with cache clear.

**Comment by jackeychina** [comment]
I have resolved it. You can download it from here - https://drive.google.com/file/d/1DV1OsriI0su3Is13j65NpOpabRlOhDTZ/view?usp=sharing

Now it will work with flutter 2.5

Enjoy :)

**Comment by Purus** [comment]
> I have resolved it. You can download it from here - https://drive.google.com/file/d/1DV1OsriI0su3Is13j65NpOpabRlOhDTZ/view?usp=sharing
> 
> Now it will work with flutter 2.5
> 
> Enjoy :)

Thanks for your time on this. By any chance, you have it GitHub so that it can be used directly in pubspec.yml and contribute too?

**Comment by Mahati9** [comment]
Is it working properly for you @Purus ? 
@jackeychina  I am getting this error while uploading pubspec via path.

```
Running "flutter pub get" in editing_pro...                     
Because every version of image_editor_pro from path depends on firexcode from path which is forbidden, image_editor_pro from path is forbidden.
So, because editing_pro depends on image_editor_pro from path, version solving failed.
pub get failed (66; So, because editing_pro depends on image_editor_pro from path, version solving failed.)
exit code 66
```

This is the pubspec file

```
version: 1.0.0+1

environment:
  sdk: ">=2.15.0-285.0.dev <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  image_editor_pro:
   path: "C:/Users/Avilain/Downloads/ImageEditorPro-master_solved/ImageEditorPro-master_solved"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
```

My flutter version is 2.6.0-12.0.pre.701
