### ISSUE TITLE
Cannot open file, path = 'C:\src\flutter\.pub-cache\_temp\dir6d9426e1\test\fixtures\invalid\n_structure_<.>.json' (OS Error: The filename, directory name, or volume label syntax is incorrect. , errno = 123) pub get failed (66; , errno = 123)) exit code 66

### ISSUE THREAD

**Issue by ghost** [zeeshux7860/ImageEditorPro#51]

**Comment by sharukhrahman97** [comment]
i have similar issue

**Comment by FaizanKamal7** [comment]
Did anyone find the fix to that?

**Comment by actumn** [comment]
I suppose it was caused by `json_ast` package which `firexcode` depends on. 
https://github.com/javiercbk/json_ast/pull/1

**Comment by spinoza1791** [comment]
still cannot run pub get, brand new install of everything, so the software is unusable without a solution here.
Cannot open file, path = 'C:\src\flutter\.pub-cache\_temp\dir6530a7c5\test\fixtures\invalid\n_structure_<.>.json' (OS Error: The filename, directory name, or volume label syntax is incorrect.
, errno = 123)
pub get failed (66; , errno = 123))

**Comment by Abhijithsp** [comment]
I have same problem tried to cache clear and flutter clean but still have problem 

```
E:\flutter\bin\flutter.bat --no-color pub get
Running "flutter pub get" in photoedit_repo...                  
Cannot open file, path = 'E:\flutter\.pub-cache\_temp\dir6aad5034\test\fixtures\invalid\n_structure_<.>.json' (OS Error: The filename, directory name, or volume label syntax is incorrect.
, errno = 123)
pub get failed (66; , errno = 123))
Process finished with exit code 66
```
**Pubyaml** 

```
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  image_editor_pro:
  firexcode:
  image_picker:
dev_dependencies:
  flutter_test:
    sdk: flutter
```

**Comment by Abhijithsp** [comment]
I have same problem tried to cache clear and flutter clean and turning on windows developer setting,deleted and .pub folder and reinstalled but still have problem

```
E:\flutter\bin\flutter.bat --no-color pub get
Running "flutter pub get" in photoedit_repo...                  
Cannot open file, path = 'E:\flutter\.pub-cache\_temp\dir6aad5034\test\fixtures\invalid\n_structure_<.>.json' (OS Error: The filename, directory name, or volume label syntax is incorrect.
, errno = 123)
pub get failed (66; , errno = 123))
Process finished with exit code 66
```
**pubspec.yaml** 

```
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  image_editor_pro:
  firexcode:
  image_picker:
dev_dependencies:
  flutter_test:
    sdk: flutter
```

**Flutter Doctor**

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.0, on Microsoft Windows [Version 10.0.19044.1620], locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Chrome - develop for the web
[!] Visual Studio - develop for Windows (Visual Studio Build Tools 2017 15.9.44)
    ✗ Visual Studio 2019 or later is required.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default
      components
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.66.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.
```
